### ISSUE TITLE
Index blockchains event in database instead of querying directly and query it from the database

### ISSUE THREAD

**Issue by sandoche** [sandoche/burn-auction-dapp#7]
## Context
Currently we are querying the blockchain rpc through serveless functions to filter events and retrieve the AuctionEnd Events and Bid Events. The problem is that the RPC allows only to filter through range of 10 000 blocks which is not enough to get our information. So we need to use a database that will store the events, and query through them.

## Todo
- [ ] Add prisma
- [ ] Create prisma model for AuctionEndEvent
- [ ]  Create prisma model for BidEvent
- [ ] Create indexing endpoint BidEvent
- [ ] Create indexing endpoint AuctionEndEvent
- [ ] The indexing endpoints should index from where it stopped (and default to FIRST_AUCTION_BLOCK) to that block number + 10000) and store it in database. Note: the indexing endpoint will be ran by a cron. 
- [ ] 2 new queries function will be created to pull data using prisma
  - [ ] These 2 new queries will be used instead of rpcFetchBiddingHistory and rpcFetchAuctionEnd
  - [ ] Updates the tests
- [ ] Update readme
